#!/bin/bash

echo "Installing TUIO-1.4 (requires CMake >= 2.8.12)"

SOFTWARE=TUIO
MAJOR_VERSION=1
MINOR_VERSION=4
RELEASE_VERSION=
VERSION=$MAJOR_VERSION.$MINOR_VERSION
PACKAGE=$SOFTWARE-$VERSION
PACKAGE_TAR_FILE=
PACKAGE_ZIP_FILE=
ROOT_DIR=$SOFTWARE
BUILD_DIR=$ROOT_DIR/build
DST_DIR=$LOCAL_SW_INSTALL_DIR/$SOFTWARE/$VERSION
PROTOCOL=https
SERVER=github.com
SERVER_DIR=BlueBrain
URL=$PROTOCOL://$SERVER/$SERVER_DIR/$SOFTWARE.git

cd $LOCAL_SW_BUILD_DIR
git clone $URL
mkdir -p $BUILD_DIR
mkdir -p $DST_DIR
cd $BUILD_DIR
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$DST_DIR
make
make install
ln -s $DST_DIR/include/osc $DST_DIR/include/oscpack

