#!/bin/bash

echo "Installing DisplayCluster-0.4"

SOFTWARE=DisplayCluster
MAJOR_VERSION=0
MINOR_VERSION=4
RELEASE_VERSION=
VERSION=$MAJOR_VERSION.$MINOR_VERSION
PACKAGE=$SOFTWARE-$VERSION
PACKAGE_TAR_FILE=$PACKAGE.tar
PACKAGE_ZIP_FILE=$PACKAGE.tar.gz
ROOT_DIR=$PACKAGE
BUILD_DIR=$ROOT_DIR/build
DST_DIR=$LOCAL_SW_INSTALL_DIR/$SOFTWARE/$VERSION
PROTOCOL=https
SERVER=github.com
SERVER_DIR=kaust-vislab
URL=$PROTOCOL://$SERVER/$SERVER_DIR/$SOFTWARE.git

cd $LOCAL_SW_BUILD_DIR
git clone $URL $PACKAGE
mkdir -p $BUILD_DIR
mkdir -p $DST_DIR
cd $BUILD_DIR
module load mpi/mpich-x86_64
cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$DST_DIR \
    -DCMAKE_INCLUDE_PATH=$LOCAL_SW_INSTALL_DIR/TUIO/1.4/include \
    -DCMAKE_LIBRARY_PATH=$LOCAL_SW_INSTALL_DIR/TUIO/1.4/lib
make
make install
module unload mpi/mpich-x86_64
