#!/bin/bash

echo "Installing ffmpeg-0.10.2"

SOFTWARE=ffmpeg
MAJOR_VERSION=0
MINOR_VERSION=10
RELEASE_VERSION=2
VERSION=$MAJOR_VERSION.$MINOR_VERSION.$RELEASE_VERSION
PACKAGE=$SOFTWARE-$VERSION
PACKAGE_TAR_FILE=$PACKAGE.tar
PACKAGE_ZIP_FILE=$PACKAGE.tar.bz2
ROOT_DIR=$PACKAGE
BUILD_DIR=$ROOT_DIR/build
DST_DIR=$LOCAL_SW_INSTALL_DIR/$SOFTWARE/$VERSION
PROTOCOL=http
SERVER=ffmpeg.org
SERVER_DIR=releases
URL=$PROTOCOL://$SERVER/$SERVER_DIR/$PACKAGE_ZIP_FILE

cd $LOCAL_SW_BUILD_DIR;
wget $URL;
bunzip2 $PACKAGE_ZIP_FILE;
tar xvf $PACKAGE_TAR_FILE;
rm -f $PACKAGE_TAR_FILE;
mkdir -p $BUILD_DIR;
mkdir -p $DST_DIR;
cd $BUILD_DIR;
../configure \
    --prefix=$DST_DIR \
    --enable-shared \
    --enable-pic
make;
make install;

