#!/bin/bash

echo "Installing GraphicsMagick-1.3.22"

SOFTWARE=GraphicsMagick
MAJOR_VERSION=1
MINOR_VERSION=3
RELEASE_VERSION=22
VERSION=$MAJOR_VERSION.$MINOR_VERSION.$RELEASE_VERSION
PACKAGE=$SOFTWARE-$VERSION
PACKAGE_TAR_FILE=$PACKAGE.tar
PACKAGE_ZIP_FILE=$PACKAGE.tar.bz2
ROOT_DIR=$PACKAGE
BUILD_DIR=$ROOT_DIR/build
DST_DIR=$LOCAL_SW_INSTALL_DIR/$SOFTWARE/$VERSION
PROTOCOL=ftp
SERVER=ftp.graphicsmagick.org
SERVER_DIR=pub
URL=$PROTOCOL://$SERVER/$SERVER_DIR/$SOFTWARE/$MAJOR_VERSION.$MINOR_VERSION/$PACKAGE_ZIP_FILE

cd $LOCAL_SW_BUILD_DIR;
wget $URL;
bunzip2 $PACKAGE_ZIP_FILE;
tar xvf $PACKAGE_TAR_FILE;
rm -f $PACKAGE_TAR_FILE;
mkdir -p $BUILD_DIR;
mkdir -p $DST_DIR;
cd $BUILD_DIR;
../configure \
    --enable-shared=yes \
    --prefix=$DST_DIR;
make;
make install;

